services:
  db:
    image: postgres:16
    container_name: order_saas_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_saas
    ports:
      - "5432:5432"
    volumes:
      - order_saas_data:/var/lib/postgresql/data

volumes:
  order_saas_data:
  
